### ISSUE TITLE
Unable to decode optional attributes

### ISSUE THREAD

**Issue by BruceBrown** [adam-fowler/xml-encoder#5]
**Description**
Unable to decode optional attributes

**To Reproduce**
```
struct MyList: Codable {
    let fixed: [FixedItems]
    let optional: [OptionalItems]
    
    struct FixedItems: Codable {
        let name: String
        let task: String
    }
    
    struct OptionalItems: Codable {
        let name: String
        let task: String
        let priority: String?
    }
}
@main
struct DemoApp: App {
    init() {
        let fileName = "test"
        guard let path = Bundle.main.path(forResource: fileName, ofType: "xml") else { return }
        let url = URL(fileURLWithPath: path)
        guard let data = try? Data(contentsOf: url),
              let xmlDocument = try? XML.Document(data: data),
              let rootElement = xmlDocument.rootElement() else {
            return
        }
        do {
            let list = try XMLDecoder().decode(MyList.self, from: rootElement)
            print("decoded")
        } catch {
            print("failed to decode, error=\(error)")
        }
        print("done")
    }
 
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
```
test.xml contents:
```
<?xml version="1.0" encoding="UTF-8"?>
<list>
    <fixed name="first fixed" task="something"/>
    <optional name="first optional" task="task 1" priority="high"/>
    <optional name="second optional" task="task 2"/>
</list>
```
**Expected behavior**
list.optional[0].priority should be "high", and instead it is nil
list.optional[1].priority should be nil, and is nil

**Platform (please complete the following information):**
 - OS: iOS emulator
 - Version of xml-encoder 0.4.0

**Additional context**

**Comment by adam-fowler** [comment]
Hi @BruceBrown do you want to test #6

**Comment by BruceBrown** [comment]
Sure, Tnx. Give me a few hours to fully wake up ;)

—Bruce

**Comment by BruceBrown** [comment]
Took me a while to get it integrated -- had to pull a fork and then copy
into the project. Anyway, I've confirmed that the fix works and I'm able to
consume optional attributes which end up being nil or a string, as expected.

Best regards,
Bruce

**Comment by adam-fowler** [comment]
This is in release [0.4.1](https://github.com/adam-fowler/xml-coding/releases/tag/0.4.1).
By the way the easiest way to have tested this from the PR would be to use the branch associated with the PR.
